microsoft/MSBuildForUnity

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/BuildProjects.proj.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/BuildProjects.proj.template.meta, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/TemplateFiles.cs
Added a quick generator of BuildProjects.proj MSBuild file to enable invoking the builds with:
dotnet msbuild BuildProjects.proj /t:Build<Platform><Config>.
And a quick bat file to build it all.
=> Generate BuildProjects.proj Helper

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/UnityProjectInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Utilities.cs
Fixing a lucky bug with new lines, the issue was made transparent because of git pulling down with '\r\n', leaving a trailing '\r' in templates resulting in success; with git pulling '\n', it didn't leave any trailing new line and fails
=> Bug Fixing New Line Issue

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/SDKProjectTemplate.csproj.template
Last week MRTK builds encountered an issue with their generated projects after a software update was pushed to the build machines. For some reason, the specific setup of the machine was causing the issue.
The issue was that MSBuild would ignore precedence of AssemblySearchPaths, which places HintPath before {TargetFrameworkPath} when resolving the assemblies, and this resulted in the .NET 4.6 (the target framework of the generated project) assembly to be chosen over the explicitly referenced one of .NET 4.7.2 (what unity uses to compile).
The fix here is to remvoe {TargetFrameworkDirectory} from the search paths, and prevent the explicit addition of targetFramework dlls.
=> Migrate Fix from MRTK

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilder.cs
This change adds `-p:NuGetInteractive=true` to the build command, and scans for ADO package feed authentication requests. The ADO auth request is logged from the build, and this is detected via a regex, but most of the string is localized so the regex is a bit different than might be expected. It looks for the non-localized prefix of `[CredentialProvider]`, looks for the ADO auth url of `https://microsoft.com/devicelogin`, and looks for the 9 character auth code. A dialog is displayed that helps the user navigate to the auth page and enter the auth code.
Clicking `OK` will take the user to a page that looks like this:
After entering the code and clicking `Next`, the authentication will be completed and NuGet restore will complete and the build will continue.
This is arguably fragile …
=> Enable interactive restore and ADO auth

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildBuildProfile.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilderEditor.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectImporter.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectReference.cs
This change moves the `AutoBuild` flag from the `MSBuildProjectReference` to the individual `MSBuildBuildProfile`s that are on the `MSBuildProjectReference`. This makes a lot more sense than just trying to guess which "profile" to auto build across all referenced projects. By default, `MSBuildProjectReference`s are created with a `Build` profile with `AutoBuild` set to `true`, so the default behavior is not changing, it just makes more sense now and is more configurable.
=> Move AutoBuild flag to each Profile

AzurePipelines/PRGate.yml, AzurePipelines/Publish.NuGet.yml, AzurePipelines/Templates/BuildMSBuildForUnityNuGetBinaries.yml, AzurePipelines/Templates/BuildMSBuildForUnityNuGetPackage.yml, AzurePipelines/Templates/PublishNuGetPackages.yml, AzurePipelines/Templates/SignBinaries.yml, AzurePipelines/Templates/SignNuGetPackages.yml
This change updates the NuGet package build to sign MSBuildForUnity.dll as well as the NuGet package itself.
- Break the existing build step into two separate steps (build and package)
- Add a step for signing binaries between building and packaging
- Add a step for signing the package
=> Sign dlls and package

.gitmodules, AzurePipelines/Publish.NuGet.yml, AzurePipelines/Templates/SignBinaries.yml, Source/MSBuildTools.Unity.NuGet/MSBuildForUnity.NuGet.sln, Source/MSBuildTools.Unity.NuGet/MSBuildForUnity.csproj
The primary change here is to sign third party components (Newtonsoft.Json and Mono.Cecil) and include them in the NuGet package:
- Update MSBuildForUnity.csproj to ensure third party components are copied to the output directory (so we can sign them), and make sure they are then packaged up with the NuGet package.
- Update the code signing steps to sign the third party components.
I also made a couple related changes::
- Replace the Mono.Cecil submodule with the actual NuGet package (an updated package was published a few days ago with the bug fixes we needed).
- Add the ComponentGovernanceComponentDetection step to check for third party components with any known problems (we shouldn't ship such components).
=> Sign third party components

Source/MSBuildTools.Unity.NuGet/Tasks/GenerateAssetId.cs, Source/MSBuildTools.Unity.NuGet/UnityMetaFileGenerator.props, Source/MSBuildTools.Unity.NuGet/UnityMetaFileGenerator.targets
CodeTaskFactory is not compatible with dotnet. Moving this into the existing dll as a custom C# based task solves this.
=> Move GenerateAssetId into a custom C# task

README.md
Updating the main readme following introductions of samples.
=> Updating the main Readme.md

README.md, Samples/SimpleNuGetDependency.Unity/Assets/NewtonsoftDependency/NewtonsoftDependency.csproj, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/DependenciesProjectTemplate.g.props.template
There are two changes here:
- Updating MSBuildForUnity NuGet package reference that is either generated or embedded in the simple sample. The new version range allows any 0.8.0- prerelease, or a 0.8.0 package as max.
- Correcting casing on main readme links
=> Updating Readme, plus version range

AzurePipelines/Publish.UPM.yml
I would like to use the same NPM pipeline to build and push release package, for that I want to increment the versions only on master branches.
=> Increment NPM Version only on Master

AzurePipelines/Publish.UPM.yml, README.md, Samples/SimpleNuGetDependency.Unity/Assets/NewtonsoftDependency/NewtonsoftDependency.csproj, Source/MSBuildTools.Unity.NuGet/MSBuildForUnity.csproj, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/DependenciesProjectTemplate.g.props.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/MSBuildForUnity.Common.props.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/package.json
I updated the building rules for CIs that would not increment (or append) the prerelease version unless we are on "release/" branch. I had to up the version to 0.8.1 because I realized I pushed 0.8.0 deleted, and now can't push it.
=> Final Prep for Release

README.md, Samples/SimpleNuGetDependency.Unity/Assets/NewtonsoftDependency/NewtonsoftDependency.csproj, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/DependenciesProjectTemplate.g.props.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/MSBuildForUnity.Common.props.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/package.json
This change improves how the project handles platform and target framework (API Compatibility set) changes. Furthermore, it makes sure to appropriately clean-up before making the switch.
This increments the version to 0.8.2 for the hotfix.
This PR is against the prerelease/0.8.2 branch which is essentially the release/0.8.1. Once we approve, I will rename prerelease/0.8.2 to release/0.8.2 and push a release.
=> Fix Platform and TargetFramework switching

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectReferenceEditor.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Exporters/TemplatedProjectExporter.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/PluginAssemblyInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Utilities.cs
This change consists of two items:
- MakeRelativeURI will produce escaped strings, so I unescape that.
- AbsoulutePath will produce excaped strings, so I use LocalPath instead
=> This change fixes the issue with spaces in project path

Directory.Build.props, Samples/SimpleNuGetDependency.Unity/Assets/NewtonsoftDependency/NewtonsoftDependency.csproj, Source/MSBuildTools.Unity.NuGet/MSBuildForUnity.csproj
This change covers some of the goals of #56, only specifically aimed at MSBuild aspects. This means:
- There is a new Directory.Build.props file at the root to centralized the versioning info
- The MSBuildForUnity.NuGet package project will use this to set the appropriate version
- The sample SimpleNuGetDependency will also rely on this to set it's dependency.
Additionally, this change also auto-increments the patch version on non-release branches.
This change doesn't cover the following:
- Mechanism for updating the templates used in generation that are part of MSBuildForUnity NPM package
- Mechanism for keeping the NPM package.json version in sync
=> Version Synchronization (MSBuild)

README.md
Updated README a bit to bring Quick Start closer to the top.
=> Small README Update

Documentation/CraftingNuGetPackages.md, README.md
Added documentation on how to extend NuGet packages to support MSBuildForUnity for consuming NuGet packages in Unity.
=> Documentation for Extending NuGet Packages

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/SDKProjectTemplate.g.props.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/AssetScriptReferenceRetargeter.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/UnityProjectInfo.cs
These changes are related to unblocking MSB4U usage in the MixedReality-SpectatorView repo.
1) Asset retargeting appears to have been written originally with the mixed reality toolkit in mind. This change removes some toolkit specific paths. However, this fix does not solve things for asmdefs that don't have a Microsoft.MixedReality* prefix.
2) A RegenerateSDKProjects function has been added that can be called from the command line. GenerateSDKProjects seems to run indefinitely when called from a cmd window.
=> Small fixes related to editor only scripts and non MRTK projects

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/CSProjectInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Exporters/TemplatedProjectExporter.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/UnityProjectInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/WinMDInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/WinMDInfo.cs.meta
Currently only managed plugins are referenced in MSBuildForUnity project generation. In some instances, we also need to include winmd references. This change introduces the concept of winmds and adds winmd references to MSBuildForUnity generated projects. 
https://github.com/microsoft/MSBuildForUnity/pull/93 is currently open and addresses all changes before 137fd4d "add winmd support"
=> Add Winmd support

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/PluginAssemblyInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/UnityProjectInfo.cs
This PR contains three fixes:
- Remap Unity.ugui in a similar fashion (but different point) as #98 
- Correct meta parsing for "All" platforms included
- Correct meta parsing for NUnit.framework.dll.meta that species "DefineConstraint" in a strange way
- Fix a 2019 Warning on platform
Fixes #97.
=> Three Fixes: Unity.ugui Issue; NUnit meta parsing; 2019/2018 warning

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs
When MSB4U is added to a brand new project, there will be a an exception thrown when settings.json file is being written because the MSBuild directory doesn't exist. So, just call CreateDirectory which will go ahead and create all directories an subdirectories in a given path (unless they exist).
=> Ensure MSBuild directory exists when the settings file is being written

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/AssemblyDefinitionInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/CSProjectInfo.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Exporters/TemplatedProjectExporter.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/UnityProjectInfo.cs
TestRunner is a strange asmdef, so added special patching for this project. The AsmDef is referenced by Test projects that always have 'UNITY_INCLUDE_TESTS' defined, and it references nunit which also has it set. However, it itself doesn't and this breaks during generated projects player compilation as no player platform includes that define.
=> Added Special Patching of TestRunner

Samples/CrossUnityDependencies.Unity/Assets/CrossUnityDependencies.Unity.msb4u.sln, Samples/IntegratedDependencies.Unity/Assets/Project.Unity.msb4u.sln, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/MSBuildForUnity.Common.props.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Exporters/TemplatedExporter/TemplatedUnityProjectExporter.cs
This is a fix on top of previous change for the Dependency project rename, to also make sure we rename it in the generated solution file.
This change also disabled the "CleanupTask" that performed a deletes in the output directory. This causes no errors thus far, and if it does it will be re-enabled; otherwise this will be removed and the issue #71 can be closed.
=> Fix Dependency name in Generated Solution File

Source/MSBuildTools.Unity.NuGet/Publish.props, Source/MSBuildTools.Unity.NuGet/Publish.targets
Updating the package filtering to use a different group later in the process.  This is supported in both dotnet SDK 2 (the old one) and 3 (the new one), whereas the old target and group went away in 3.
=> New dotnet SDK support

Samples/CrossUnityDependencies.Unity/Assets/CrossUnityDependencies.Unity.Dependencies.msb4u.csproj, Samples/CrossUnityDependencies.Unity/README.md, Samples/IntegratedDependencies.Unity/Assets/Project.Unity.Dependencies.msb4u.csproj, Samples/IntegratedDependencies.Unity/README.md, Samples/SimpleNuGetDependency.Unity/Assets/Project.Unity.Dependencies.msb4u.csproj, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/DependenciesProjectTemplate.csproj.template, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/DependenciesProjectTemplate.g.props.template
In projects that are built for AsmDef, we don't know the target framework until we import the platform props, and that depends on the UnityConfig/UnityPlatform pairing we are building with.
For the top-level dependencies project we do, it's specifies in the common props file, so just set it immediately. This fixes an issue with VS2019.
=> Dependency Project Explicit Target Framework

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/NuGet.config, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/NuGet.config.meta, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/Templates/TemplateFiles.cs
While retrieving the MRTK NuGet packages via MSBuildForUnity, you first need to add ```https://pkgs.dev.azure.com/UnityDeveloperTools/MSBuildForUnity/_packaging/UnityDeveloperTools/nuget/v3/index.json ``` as a source.  This change removes adding an additional source to enable MRTK NuGet package installation with one step.
- Added NuGet.config to TemplateFiles.cs
- Moved Nuget.config to the TemplateFiles directory
- #99
=> Added NuGet.config to TemplateFiles

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildToolsConfig.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildToolsConfig.cs.meta
This change detects changes that Unity sees to assembly definition or C# project files and regenerates the project if needed. It also will perform a clean if a C# project file has been removed.
Fixes #88.
=> Detect Modifications to Assembly Definitions or C# Projects

AzurePipelines/Publish.UPM.yml, Directory.Build.props, README.md, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/Scripts/MSBuildTools.cs, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/package.json
This change does a couple of things:
- Upgrades versions, and fixes MSB4U_RevisionVersion_PreIncrement to reference MSB4U_RevisionVersion instead of specifying duplicate versions. (This is done before the increment).
- Updates the increment not to happen on prerelease versions.
- Updates README.md a bit.
=> Upgrading version to 0.9.0

AzurePipelines/Publish.UPM.yml, AzurePipelines/Scripts/IncrementUPMVersion.ps1
The new increment logic does the following:
- Increment the Patch version and set prerelease ID on all branches other than prerelease and release
- Set the prerelease ID on prerelease branches.
=> Update UPM Increment Logic

README.md
The version '0.9.1', being referred to in the README.md, throws an error while opening up the Unity project, indicating the aforementioned version does not exist. Changing it to the latest released version solves the problem.
=> Fix README.md to point to the latest release of the MSBuildForUnity

Source/MSBuildTools.Unity.NuGet/UnityMetaFileGenerator.targets
Address #146 where Unity 2019 no longer recognizes the extraneous line breaks MSBuildForUnity generates.
Before (no longer recognized):
```
fileFormatVersion: 2
guid: beddd2171b0a2d63e917dd0a6fd71e4a
PluginImporter:
serializedVersion: 2
platformData:
- first:
Editor: Editor
second:
enabled: 1
settings: {}
executionOrder: {}
```
After (notice no line breaks after platformData):
```
fileFormatVersion: 2
guid: beddd2171b0a2d63e917dd0a6fd71e4a
PluginImporter:
serializedVersion: 2
platformData:
- first:
Editor: Editor
second:
enabled: 1
settings: {}
executionOrder: {}
```
=> Remove extraneous linebreaks from generated .meta file

Samples/IntegratedDependencies.Unity/Assets/NuGet.config, Samples/SimpleNuGetDependency.Unity/Assets/NewtonsoftDependency/NuGet.config, Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectGenerator/MSBuildTemplates/NuGet.config
Update samples to be compliant with automatic NuGet security analysis injected in ADO pipelines. See https://aka.ms/nugetsecurityanalysis for more details but this essentially boils down to:
1. Ensuring `<clear/>` statements are in each nuget.config file in the repo
2. nuget.config only specifies a singular nuget feed
Since these are samples, the change adds 1 above and comments out references to the `MSBuildForUnity` feed with the expectation that one would uncomment them from the sample when testing this out manually. This is currently consistent with the documentation that a special feed for the MSBuildForUnity is currently required.
=> Update samples to be compliant with NuGet security analysis in Azure pipelines

Source/MSBuildTools.Unity/Packages/com.microsoft.msbuildforunity/Editor/ProjectBuilder/MSBuildProjectBuilder.cs
msbuild call was not quoted, so any space would break the build (either in the project name or the parent folder containing the project).
Fix #132.
=> Added support for project names with spaces
